-- Prüfwerk: Kunden + UVV-Protokolle
-- Im Supabase Dashboard unter SQL Editor einfügen und einmal ausführen.

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  customer_number text default '',
  contact text default '',
  phone text default '',
  email text default '',
  street text default '',
  postal_code text default '',
  city text default '',
  notes text default '',
  status text not null default 'Aktiv'
);

create table if not exists public.protocols (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  protocol_number text not null unique,
  customer_id bigint not null references public.customers(id) on delete restrict,
  inspection_date date not null,
  inspector text not null,
  object_name text not null,
  object_number text default '',
  result text not null,
  notes text default '',
  next_inspection date,
  checks jsonb not null default '[]'::jsonb
);

alter table public.customers enable row level security;
alter table public.protocols enable row level security;

drop policy if exists "Angemeldete Benutzer verwalten Kunden" on public.customers;
create policy "Angemeldete Benutzer verwalten Kunden"
on public.customers
as permissive
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Angemeldete Benutzer verwalten Protokolle" on public.protocols;
create policy "Angemeldete Benutzer verwalten Protokolle"
on public.protocols
as permissive
for all
to authenticated
using (true)
with check (true);

create index if not exists protocols_customer_id_idx on public.protocols(customer_id);
create index if not exists protocols_inspection_date_idx on public.protocols(inspection_date desc);
